# Entity limits
MAX_WISHLISTS_PER_USER = 50
MAX_ITEMS_PER_WISHLIST = 100

MAX_WISHLIST_TITLE_LENGTH = 100
MAX_WISHLIST_DESCRIPTION_LENGTH = 500
MAX_ITEM_TITLE_LENGTH = 200
MAX_ITEM_NOTE_LENGTH = 500
MAX_GUEST_NAME_LENGTH = 50

# Pagination defaults
DEFAULT_PAGE_SIZE = 20
DEFAULT_ITEMS_PAGE_SIZE = 50
MAX_PAGE_SIZE = 100

# Rate limits
LOGIN_RATE_LIMIT = "5/minute"
REGISTER_RATE_LIMIT = "3/minute"
URL_PARSER_RATE_LIMIT = "10/minute"
GUEST_RECOVER_RATE_LIMIT = "3/minute"

# WebSocket
WS_PING_INTERVAL = 30  # seconds

# URL parser
URL_PARSER_TIMEOUT = 5  # seconds
URL_PARSER_MAX_CONTENT_LENGTH = 1_000_000  # 1 MB

# Image upload
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5 MB
ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/webp"}

# Guest recovery token
GUEST_RECOVERY_TOKEN_EXPIRE_MINUTES = 60  # 1 hour
